name: "Build & Test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  actions: read
  contents: read

jobs:
  build:
    name: "Build & Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Set up Go
        id: install_go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build
        id: build
        run: |
          go build -v ./...

      - name: Test
        id: test
        run: |
          go test -v ./...
